# Generated by Django 3.0.3 on 2020-02-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0002_post_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='industry',
            field=models.CharField(choices=[('Technology', 'technology'), ('Business', 'business'), ('General', 'general')], max_length=200),
        ),
    ]
